// Build the seed SQL for the Freeside adventure.
//
// Reads the original hand-authored content (`adventure-source.ts` — formerly the
// React app's `src/data.ts`) and emits `db/adventure.sql`: a normalized dump with
// 1:M child rows and the M:N join rows (characters<->locations via named-NPC
// appearances, location<->location via connected areas) resolved from codes to ids.
//
//   npm run build:adventure   ->  db/adventure.sql
//   npm run db:load:local     ->  import into local D1
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { characters, locations, dungeons, pages } from './adventure-source';
import { SCHEMA } from '../src/db';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'db', 'adventure.sql');

const ADV_ID = 'freeside';
const SLUG = 'freeside';
const TITLE = 'Freeside';
const OVERVIEW = 'A run-from-the-page sandbox adventure set in the lawless free port of Freeside.';

// --- SQL value helpers ------------------------------------------------------
const esc = (v: unknown): string => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const num = (v: unknown): string => (v == null || Number.isNaN(Number(v)) ? 'NULL' : String(Number(v)));
const jsonOrNull = (v: unknown): string =>
  v == null || (Array.isArray(v) && v.length === 0) ? 'NULL' : esc(JSON.stringify(v));

const img = (kind: string, code: unknown): string =>
  code ? esc(`/img/${kind}/${String(code)}.png`) : 'NULL';

// --- ids: match the original React `addId` reading-order numbering -----------
// `pages = addId([...])` (in adventure-source) mutates each entity's `.id`/`.page`
// to the value the React app displayed: locations 1,2,3…, characters 1,2,3…,
// dungeons 1,3,5… (dCount += 2). We reuse those exact ids. Entities not in the
// reading order (e.g. the unplaced character `cloaked`) get a trailing id so
// their M:N links still resolve.
const pageCodes = new Set((pages as any[]).filter(Boolean).map((p: any) => String(p.code)));
function idMap(arr: any[]): Map<string, number> {
  const placed = arr.filter((o) => pageCodes.has(String(o.code)));
  let next = placed.reduce((m, o) => Math.max(m, Number(o.id) || 0), 0) + 1;
  const map = new Map<string, number>();
  arr.forEach((o) => map.set(String(o.code), pageCodes.has(String(o.code)) ? Number(o.id) : next++));
  return map;
}
const charId = idMap(characters as any[]);
const locId = idMap(locations as any[]);
const dungId = idMap(dungeons as any[]);
const pageOf = (o: any): string => (pageCodes.has(String(o.code)) ? num(o.page) : 'NULL');

const lines: string[] = [];
const w = (s: string) => lines.push(s);

w('-- Generated by scripts/build-adventure.ts — do not edit by hand.');
w('PRAGMA foreign_keys=OFF;');
w('BEGIN TRANSACTION;');

// Schema first (idempotent) so the seed is self-contained for `wrangler d1 execute`.
// Single source of truth: the same SCHEMA the Worker creates lazily at runtime.
for (const stmt of SCHEMA) w(stmt.replace(/\s+/g, ' ').trim() + ';');

// Idempotent re-seed: clear this adventure's content first.
for (const t of [
  'character_dialogue', 'character_quests', 'character_misc',
  'location_events', 'location_random_npcs', 'location_characters', 'location_connections',
  'dungeon_rooms', 'dungeon_monsters', 'dungeon_misc', 'characters', 'locations', 'dungeons', 'pages',
]) {
  // child tables don't carry adventure_id; clearing the parents + a fresh load is fine for a single-adventure seed.
  w(`DELETE FROM ${t}${['characters', 'locations', 'dungeons', 'pages'].includes(t) ? ` WHERE adventure_id = ${esc(ADV_ID)}` : ''};`);
}
w(`DELETE FROM adventures WHERE id = ${esc(ADV_ID)};`);
w(
  `INSERT INTO adventures (id, owner_id, slug, title, overview, created_at) ` +
  `VALUES (${esc(ADV_ID)}, NULL, ${esc(SLUG)}, ${esc(TITLE)}, ${esc(OVERVIEW)}, 0);`,
);

// --- characters -------------------------------------------------------------
characters.forEach((c: any) => {
  const id = charId.get(String(c.code))!;
  w(
    `INSERT INTO characters (id, adventure_id, code, name, title, age, race, alignment, detail_one, ` +
    `strength, dexterity, constitution, intelligence, wisdom, charisma, ` +
    `challenge_rating, armor_class, hit_points, speed, passive_perception, proficiency_bonus, ` +
    `attack_json, spells_json, skills_json, roleplay_inspiration, motivation, dm_notes, visual_description, image, page) VALUES (` +
    [
      id, esc(ADV_ID), esc(c.code), esc(c.name ?? ''), esc(c.title ?? ''), num(c.age), esc(c.race ?? ''),
      esc(c.alignment ?? ''), esc(c.detailOne ?? ''),
      num(c.strength), num(c.dexterity), num(c.constitution), num(c.intelligence), num(c.wisdom), num(c.charisma),
      num(c.challengeRating), num(c.armorClass), num(c.hitPoints), num(c.speed), num(c.passivePerception), num(c.proficiencyBonus),
      jsonOrNull(c.attack ?? null), jsonOrNull(c.spells ?? []), jsonOrNull(c.skills ?? []),
      esc(c.roleplayInspiration ?? ''), esc(c.motivation ?? ''), esc(c.dmNotes ?? ''), esc(c.visualDescription ?? ''),
      img('characters', c.code), pageOf(c),
    ].join(', ') + ');',
  );
  (c.dialogue ?? []).forEach(([type, text]: [string, string], ord: number) =>
    w(`INSERT INTO character_dialogue (character_id, type, text, ord) VALUES (${id}, ${esc(type)}, ${esc(text)}, ${ord});`));
  (c.quests ?? []).forEach(([prompt, reward]: [string, string], ord: number) =>
    w(`INSERT INTO character_quests (character_id, prompt, reward, ord) VALUES (${id}, ${esc(prompt)}, ${esc(reward)}, ${ord});`));
  (c.misc ?? []).forEach(([key, value]: [string, string], ord: number) =>
    w(`INSERT INTO character_misc (character_id, key, value, ord) VALUES (${id}, ${esc(key)}, ${esc(value)}, ${ord});`));
});

// --- locations + M:N relations ---------------------------------------------
locations.forEach((l: any) => {
  const id = locId.get(String(l.code))!;
  w(
    `INSERT INTO locations (id, adventure_id, code, name, inspiration, exterior, interior, ` +
    `detail_one, detail_two, crowd, dm_notes, image, page) VALUES (` +
    [
      id, esc(ADV_ID), esc(l.code), esc(l.name ?? ''), esc(l.inspiration ?? ''), esc(l.exterior ?? ''),
      esc(l.interior ?? ''), esc(l.detailOne ?? ''), esc(l.detailTwo ?? ''), esc(l.crowd ?? ''),
      esc(l.dmNotes ?? ''), img('locations', l.code), pageOf(l),
    ].join(', ') + ');',
  );
  (l.events ?? []).forEach((text: string, ord: number) =>
    w(`INSERT INTO location_events (location_id, text, ord) VALUES (${id}, ${esc(text)}, ${ord});`));
  (l.randomNpcs ?? []).forEach((r: any, ord: number) =>
    w(
      `INSERT INTO location_random_npcs (location_id, name, race, job, description, dialogue, ord) VALUES (` +
      `${id}, ${esc(r.name)}, ${esc(r.race)}, ${esc(r.job)}, ${esc(r.description)}, ${esc(r.dialogue)}, ${ord});`,
    ));
  // M:N — named characters appearing here.
  (l.namedNpcs ?? []).forEach(([code, description]: [string, string], ord: number) => {
    const cid = charId.get(String(code));
    if (cid) w(`INSERT OR IGNORE INTO location_characters (location_id, character_id, description, ord) VALUES (${id}, ${cid}, ${esc(description)}, ${ord});`);
  });
  // M:N — connected areas (self-join).
  (l.connectedAreas ?? []).forEach((code: string) => {
    const other = locId.get(String(code));
    if (other) w(`INSERT OR IGNORE INTO location_connections (location_id, connected_location_id) VALUES (${id}, ${other});`);
  });
});

// --- dungeons + 1:M rooms / monsters ---------------------------------------
dungeons.forEach((d: any) => {
  const id = dungId.get(String(d.code))!;
  w(
    `INSERT INTO dungeons (id, adventure_id, code, title, dm_notes, image, page) VALUES (` +
    `${id}, ${esc(ADV_ID)}, ${esc(d.code)}, ${esc(d.title ?? '')}, ${esc(d.dmNotes ?? '')}, ${img('dungeons', d.code)}, ${pageOf(d)});`,
  );
  (d.misc ?? []).forEach(([key, value]: [string, string], ord: number) =>
    w(`INSERT INTO dungeon_misc (dungeon_id, key, value, ord) VALUES (${id}, ${esc(key)}, ${esc(value)}, ${ord});`));
  (d.rooms ?? []).forEach((rm: any, ord: number) =>
    w(
      `INSERT INTO dungeon_rooms (dungeon_id, num, title, description, events_json, ord) VALUES (` +
      `${id}, ${num(rm.num)}, ${esc(rm.title ?? '')}, ${esc(rm.desc ?? '')}, ${jsonOrNull(rm.events ?? [])}, ${ord});`,
    ));
  (d.monsters ?? []).forEach((m: any, ord: number) =>
    w(
      `INSERT INTO dungeon_monsters (dungeon_id, code, name, race, alignment, ` +
      `strength, dexterity, constitution, intelligence, wisdom, charisma, ` +
      `challenge_rating, armor_class, hit_points, speed, passive_perception, proficiency_bonus, attack_json, skills_json, ord) VALUES (` +
      [
        id, esc(m.code ?? ''), esc(m.name ?? ''), esc(m.race ?? ''), esc(m.alignment ?? ''),
        num(m.strength), num(m.dexterity), num(m.constitution), num(m.intelligence), num(m.wisdom), num(m.charisma),
        num(m.challengeRating), num(m.armorClass), num(m.hitPoints), num(m.speed), num(m.passivePerception), num(m.proficiencyBonus),
        jsonOrNull(m.attack ?? null), jsonOrNull(m.skills ?? []), ord,
      ].join(', ') + ');',
    ));
});

// --- pages (reading order) --------------------------------------------------
const kindOf = (p: any): 'location' | 'character' | 'dungeon' | null => {
  if (p == null) return null;
  if (p.exterior !== undefined) return 'location';
  if (p.dialogue !== undefined) return 'character';
  if (p.rooms !== undefined) return 'dungeon';
  return null;
};
const idFor = (kind: string, code: unknown): number | undefined =>
  kind === 'location' ? locId.get(String(code)) : kind === 'character' ? charId.get(String(code)) : dungId.get(String(code));

let position = 0;
let skipped = 0;
for (const p of pages as any[]) {
  const kind = kindOf(p);
  const refId = kind ? idFor(kind, p.code) : undefined;
  if (!kind || !refId) { skipped++; continue; }
  w(`INSERT INTO pages (adventure_id, position, kind, ref_id) VALUES (${esc(ADV_ID)}, ${position}, ${esc(kind)}, ${refId});`);
  position += 1;
}

w('COMMIT;');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join('\n') + '\n');
console.log(
  `Wrote ${OUT}\n` +
  `  ${characters.length} characters, ${locations.length} locations, ${dungeons.length} dungeons\n` +
  `  ${position} pages (${skipped} unresolved page refs skipped)`,
);
