import { CLIENT_RENEG_LIMIT } from "tls";

export const getNpc = (id: number) => {
    return characters.filter((npc) => {
        return npc.id === id
    })[0] as Character
  };

  export const getLocation = (id: number) => {
    return locations.filter((npc) => {
        return npc.id === id
    })[0] as Location
  };


export const toTitle = (val: string) => {
    return val.replace(/([a-z])([A-Z])/g, "$1 $2");
  };


export enum CC {
    ann="ann", 
    artok="artok", 
    ban="ban",
    bosph="bosph",
    boz="boz",
    caspian="caspian",
    chit="chit",
    cloaked="cloaked",
    conrad="conrad",
    crap="crap",
    dark="dark",
    dragon="dragon",
    lobi="lobi",
    gods="gods",
    master="master",
    may="may",
    planithr="planithr",
    scholars="scholars",
    torbin="torbin",
    trap="trap",
    queen="queen",
    yondo="yondo",
    wanwan="wanwan",
    zaza="zaza",
}    

export enum LC {
    ball="ball",
    bank="bank",
    club="club",
    comune="comune",
    convoy="convoy",
    court="court",
    gallery="gallery",
    gate="gate",
    glad="glad",
    land="land",
    mound="mound",
    library="library",
    merchant="merchant",
    orc="orc",
    opera="opera",
    pcafe="pcafe",
    yards="yards",
    ghost="ghost",
}

export interface RandomNpc {
    name: string;
    race: string;
    job: string;
    description: string;
    dialogue: string;
}

export interface Attack {
    description?: string;
    damage: string;
    bonus: number;
    range: number;
    multi?: number;
}

export interface Skill {
    [key: string]: number
}



export interface CharacterConnection {
    id: number;
    type: string;
    description: string;
}

// const sizes = ["xs", "sm", "md", "lg", "xl"] as const

export type Attributes = "constitution" | "strength"


enum Skills {
    Acrobatics = "Acrobatics",
    AnimalHandling = "Animal Handling",
    Arcana = "Arcana",
    Athletics = "Athletics",
    Deception = "Deception",
    History = "History",
    Insight = "Insight",
    Intimidation = "Intimidation",
    Investigation = "Investigation",
    Medicine = "Medicine",
    Nature = "Nature",
    Perception = "Perception",
    Performance = "Performance",
    Persuasion = "Persuasion",
    Religion = "Religion",
    SlieghtofHand = "Slieght of Hand",
    Stealth = "Stealth",
    Survival = "Survival",
  }


export type Character =  {    
    code: CC;
    age: number;
    race: string;
    notoriety: string;
    page: number;
    id?: number;
    name: string,
    title: string,
    strength: number;
    dexterity: number;
    constitution: number;    
    intelligence: number;    
    wisdom: number;    
    charisma: number;    
    challengeRating: number;
    armorClass: number;
    hitPoints: number;
    speed: number;
    background: string;
    passivePerception: number;
    proficiencyBonus: number;
    attack?: Attack;
    spells: string[];
    alignment: string;
    roleplayInspiration: string;
    motivation: string;
    dmNotes: string;
    characterConnections: CharacterConnection[];
    visualDescription: string;
    introduction: string;
    question: string;
    ideal: string;
    bond: string;
    flaw: string;
    skills: Skills[]
    rewards: string;
    plotFlower: string;
    plotConvoy: string;
    plotParty: string;
    plotArena: string;
    plotKaiju: string;
}

// ===== Characters ======================


export const characters: Character[] = [
    {
        code: CC.ann,
        age: 19,
        race: "human",
        notoriety: "None, totally new, and a bit too timid to earn attention",    
        page: 1,
        id: 1,
        name: "Ann",
        title: "Newby captain",
        strength: 10,        
        dexterity: 14,
        constitution: 10,                
        intelligence: 12,                
        wisdom: 9,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 14,
        hitPoints: 45,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 2,
            damage: "2d6",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Newvous Starlet, Princess Leia, Mulan",
        motivation: "Wants to command her own fleet one day",
        dmNotes: "Her main hook is her potion being used for the party or other profits. She's a bit niave and will be go along with what the players say.",
        characterConnections: [],
        visualDescription: "A plainly dressed young woman, standing on her own and being ignored.",
        introduction: "Hello, I'm Ann.",
        question: "How much do you think my potion is worth?",
        background: "I don't want to be a nobody like the people from my villiage, so I came here.",
        ideal: "I've got a dream to be a big merchant one day.",
        bond: "Once I've become something, I can return to my villiage and make them proud.",
        flaw: "I know what I want, and don't think you can change my mind.",
        skills: [Skills.AnimalHandling, Skills.Athletics, Skills.Nature],
        rewards: "She has access to a potion what makes the drinkers flowing tie-dye colors for a couple hours, and harmlessly wears off.",
        plotFlower: "If she finds out about she'll be tempted to try and sell it, but won't betray the party.",
        plotConvoy: "She doesn't want to join the Convoy, but admires them.",
        plotParty: "Her potion will be a big boon to the party.",
        plotArena: "",
        plotKaiju: ""
    
    },

    // ++++  C1 - Bozfield, Pirate Captain ++++
    {
        code: CC.boz,
        age: 28,
        race: "human",
        notoriety: "All Freeside",    
        page: 1,
        id: 1,
        name: "Bozfield",
        title: "Beautiful Pirate Captain",
        strength: 13,        
        dexterity: 12,
        constitution: 12,                
        intelligence: 8,                
        wisdom: 8,        
        charisma: 18,
        challengeRating: 2,
        armorClass: 14,
        hitPoints: 45,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 2,
            damage: "2d6",                        
        },
        spells: [],
        alignment: "Chaotic Good",
        roleplayInspiration: "Gaston, Che Guevara, Han Solo. He’s so attractive no one ever says no to him.",
        motivation: "Wants to recruit people to fight the Convoy.",
        dmNotes: "This is the most anti-Convoy NPC.",
        characterConnections: [],
        visualDescription: "The most attractive person any of the players have ever seen. A group of people swoon around him, doing whatever he wants.",
        introduction: "I am Bozfield, the most famous pirate of the seas!",
        question: "What do you think of the Convoy",
        background: "I lived my whole life with the pirates",
        ideal: "My people fight all empires, shinning a beacon of freedom to the world.",
        bond: "I will gladly give my life for my people",
        flaw: "Im not used to people saying no to me.",
        skills: [Skills.Performance, Skills.Persuasion, Skills.Athletics],
        rewards: "We think there\"s a fleet of Convoy ships arriving soon.",
        plotFlower: "None. He would destory the flower if he found out about it.",
        plotConvoy: "He's the main anti-Convoy NPC/Leader.",
        plotParty: "will attend and try to be a big deal",
        plotArena: "Will meet the players after they get into club delux",
        plotKaiju: "hell try and fight"
    
    },
    {
        code: CC.conrad,
        age: 45,
        race: "human",
        notoriety: "No one really knows him, he could be any Convoy official to most people.",    
        page: 2,
        id: 2,
        name: "Conrad",
        title: "Local Convoy Chief",
        strength: 11,        
        dexterity: 11,
        constitution: 11,                
        intelligence: 13,                
        wisdom: 14,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Used Car Salesman, Convoy Fanboy, Chip on his Shoulder",
        motivation: "Want's to establish a new Convoy Port in Freeside, and be to promoted it's manager.",
        dmNotes: "He's resentful about being passed up for promotion, but will act in a way that maintains the moral high ground as much as possible.",
        characterConnections: [],
        visualDescription: "An aging but healthy sailor. Well kept, but lightly decorated uniform.",
        introduction: "Hello, I'm Conrad, Chief of this outpost. How can the Convoy help you?",
        question: "How much do you know about the Convoy?",
        background: "I've been sailing merchant ships since I was a boy, and with the Convoy for the last 20 years.",
        ideal: "Adventure and Trade are the meaning of life.",
        bond: "The Convoy helps those who believe in peace and freedom.",
        flaw: "There have been certain cities where the Convoy became a dominant force, but you can't blame us for having the best system.",
        skills: [Skills.Insight, Skills.Survival, Skills.Stealth],
        rewards: "We think there\"s a fleet of Convoy ships arriving soon.",
        plotFlower: "If he finds out about it, he'll use it to get promoted.",
        plotConvoy: "He wants the secret port to sucede and becomes it's new chief.",
        plotParty: "Won't go, he works at night.",
        plotArena: "Thinks it's a waste of time.",
        plotKaiju: "He'll help organize to fight it. Even teaming up with enemies."
    
    },
    {
        code: CC.crap,
        age: 100,
        race: "orc",
        notoriety: "Most people know he's the current orc boss, but they know it changes frequently.",    
        page: 1,
        id: 1,
        name: "Crap Face",
        title: "Orc gang leader",
        strength: 18,        
        dexterity: 13,
        constitution: 15,                
        intelligence: 8,                
        wisdom: 10,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Neutral",
        roleplayInspiration: "40k Orks, Cockny gang leader, boxing champ",
        motivation: "Wants to be the strongest, but also preserve the orc lifestyle.",
        dmNotes: "He's the person to talk to if you need to convince the orcs to do anything.",
        characterConnections: [],
        visualDescription: "A huge orc with only a fewer tatters of clothes and no weapons.",
        introduction: "I'm Crap face, I'm the toughest orc in the world.",
        question: "You looking for a fight?",
        background: "Orcs from all over come here for the true purpose of life, fighting!",
        ideal: "We don't fight for kings or for gold, only for strength!",
        bond: "We're living a perfect life here, I'll do anything to protect that.",
        flaw: "I don't care what happens on the rest of the island as long as we're left alone.",
        skills: [Skills.Intimidation, Skills.Athletics, Skills.Survival],
        rewards: "If you beat him in a fist fight, you'll become the new Orc boss.",
        plotFlower: "He doesn't care about it at all, but thinks immortality is for weaklings.",
        plotConvoy: "He won't care about it unless he feels the orc neighborhood is threatened.",
        plotParty: "The orcs can be used to provide security.",
        plotArena: "He thinks fighting for prizes is stupid.",
        plotKaiju: "They'll rally to help defend the city."    
    },
    {
        code: CC.cloaked,
        age: 0,
        race: "human.",
        notoriety: "Only the other flower eaters know what she's doing. About a dozen people suspect she exists, but don't know her exact nature.",    
        page: 1,
        id: 1,
        name: "Lapish",
        title: "Immortal Flower Tender",
        strength: 11,        
        dexterity: 11,
        constitution: 11,                
        intelligence: 13,                
        wisdom: 14,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Evil",
        roleplayInspiration: "Joker, Serial Killer, Golum",
        motivation: "Wants to protect the flower at all costs, but has gone crazy from living so long and changing identities.",
        dmNotes: "They're the main antagonist and having be trying to maintain the status quo on the island all these years.",
        characterConnections: [],
        visualDescription: "Very innocuious in a purple cloak.",
        introduction: "Hello there, don't worry about my name.",
        question: "I'm looking for some new friends, what brings you to Freeside?",
        background: "I've lived in Freeside a long time. I hope it never changes.",
        ideal: "I will live forever, and preserve the memories of those chosen to find the flower!",
        bond: "All that matters is that me and my memories continue.",
        flaw: "I was chosen to be the caretaker of the flower.",
        skills: [Skills.Insight, Skills.Perception, Skills.Persuasion],
        rewards: "",
        plotFlower: "She's gone crazy from eating the flower petals, and thinks she's been chosen as it's protector.",
        plotConvoy: "She doesn't want the Convoy moving",
        plotParty: "She'll show up, but keep to herself. She might try to sabotage it just to maintain the status quo of the Eternal Ball.",
        plotArena: "None.",
        plotKaiju: "she'll be happy that it gets summoned since it prevents people from coming to the island."    
    },
    {
        code: CC.artok,
        age: 60,
        race: "human",
        notoriety: "Considered a local eccentric in the comune who talks a little too much.",    
        page: 1,
        id: 1,
        name: "Artok",
        title: "Sculture shop owner.",
        strength: 13,        
        dexterity: 13,
        constitution: 10,                
        intelligence: 13,                
        wisdom: 14,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Good",
        roleplayInspiration: "Ranty guy at a cafe.",
        motivation: "",
        dmNotes: "He's meant to give an alternate perspective on Freeside, and give players clues about the ghost house and secret base.",
        characterConnections: [],
        visualDescription: "Burly and wearing workshop clothes and covered in dust and dirt.",
        introduction: "Well hello, what brings you travllers to our community.",
        question: "Do you really think anyone in Freeside actually cares about each other?",
        background: "I came to Freeside as a refugee, and look at the community I've become a part of. ",
        ideal: "Everyone thinks there's other worlds out there, I don't believe it, there's just this one!",
        bond: "I'll do anything to protect our commnue. It's my whole life.",
        flaw: "No one in the districts has any morales, they're a bunch of self centered adult children!",
        skills: [Skills.Nature, Skills.History, Skills.Survival],
        rewards: "",
        plotFlower: "He can point people towards the ghost house.",
        plotConvoy: "He doesn't actually care if the convoy moves in, he's not worried if the districts come or go.",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.ban,
        age: 45,
        race: "human",
        notoriety: "Has a small group of followers, but she tries to not encourage them.",    
        page: 1,
        id: 1,
        name: "Ban",
        title: "Englighted Master",
        strength: 11,        
        dexterity: 11,
        constitution: 11,                
        intelligence: 13,                
        wisdom: 14,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Aang, Splinter, Gainan",
        motivation: "",
        dmNotes: "She's here for mood, and to give players clues about other chatacters alignments.",
        characterConnections: [],
        visualDescription: "A plain grey robbed woman mediating on a cushion.",
        introduction: "Hello seekers, I am Ban.",
        question: "Who's true nature do you seek?",
        background: "I am only a witness to the comings and goings of the world.",
        ideal: "We live in an age of strife, bound to last another 10,00 years. All seek gain and conflict. What can we do but endure?",
        bond: "I must bare witness to the truth of the world, and spread compassion.",
        flaw: "None?",
        skills: [],
        rewards: "She'll tell players the alignment of one NPC. Players just have to hold her hand and think of the NPC.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "If the players throw a good party, she'll show up and complement then on spreading joy.",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.bosph,
        age: 25,
        race: "tiefling",
        notoriety: "Everyone who pays attention to the areana knows her as a promoter.",    
        page: 1,
        id: 1,
        name: "Bospherus",
        title: "Gladiator Promoter",
        strength: 15,        
        dexterity: 10,
        constitution: 12,                
        intelligence: 10,                
        wisdom: 10,        
        charisma: 13,
        challengeRating: 2,
        armorClass: 14,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Neutral",
        roleplayInspiration: "Don King, Circus ring leader, Street magician.",
        motivation: "Wants to find hidden gem fighters and make money off them.",
        dmNotes: "She's the entry point into the getting into galtiator fights.",
        characterConnections: [],
        visualDescription: "A bousterous tiefling with exotic robes and causally casts cantrips while talking.",
        introduction: "You look like a tough bunch, how about you take a swing in the areana?",
        question: "Don't you wanna make some money, maybe get some fame while you're at it?",
        background: "I've always been a bit flamboyant, this work suits me perfectly.",
        ideal: "Well it never hurts to make a bit of gold while you're having some fun.",
        bond: "Well, we've all got to look out for ourselves first.",
        flaw: "Perhaps you could lose a match, just this once.",
        skills: [],
        rewards: "",
        plotFlower: "If she finds out about it she might try to make a buck off it.",
        plotConvoy: "She can be swayed to whichever side makes more money, including rallying galdiators to fight for one side.",
        plotParty: "She'll try to make money off it one way or another.",
        plotArena: "She's the main entry to this plot.",
        plotKaiju: ""    
    },
    {
        code: CC.caspian,
        age: 19,
        race: "Half Elf",
        notoriety: "Know in all as Freeside as a brilliant merchant and business person.",    
        page: 1,
        id: 1,
        name: "Caspian",
        title: "Brillaint Merchant",
        strength: 8,        
        dexterity: 10,
        constitution: 9,                
        intelligence: 20,                
        wisdom: 20,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 9,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Business Sherlock Holms, Boy Genius, literally smarter than everyone else.",
        motivation: "Maintain trade, peace and the open exchange of ideas.",
        dmNotes: "He's the middle ground opinion about the convoy. He thinks they're too big to fight.",
        characterConnections: [],
        visualDescription: "Short young man, smartly dressed with little adornment.",
        introduction: "Ah new friends, I am Caspian, a humble merchant.",
        question: "So how do you think the good people of Freeside should handle the Convoy?",
        background: "I was born here.",
        ideal: "There are only 2 ways people interact, trade, and conflict, which one do you think I believe in?",
        bond: "Freeside must continue no matter what. Just because it's survied many empires doesn't mean it'll go on forever.",
        flaw: "Sometimes we must be willing to give things up in order to keep what really matters.",
        skills: [Skills.Insight, Skills.History, Skills.Investigation],
        rewards: "",
        plotFlower: "Will want to use it as a bargaining chip to maintain Freeside's Autonomy.",
        plotConvoy: "Believes in letting them have some territory, but not too much.",
        plotParty: "Will invest if he thinks it's a good idea.",
        plotArena: "",
        plotKaiju: "Will help rally people to fight it."    
    },
    {
        code: CC.chit,
        age: 99999,
        race: "",
        notoriety: "",    
        page: 1,
        id: 1,
        name: "Chitalogoth",
        title: "Eldar Being",
        strength: 20,        
        dexterity: 20,
        constitution: 20,                
        intelligence: 20,                
        wisdom: 20,        
        charisma: 6,
        challengeRating: 2,
        armorClass: 25,
        hitPoints: 1000,
        speed: 30,
        passivePerception: 20,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Evil",
        roleplayInspiration: "Cthulu, Hellraiser, Dracula",
        motivation: "Gains power through the struggles of people in his VR simulation.",
        dmNotes: "Is meant as a fun combat encounter, and give players a reward that people in Freeside will recognize.",
        characterConnections: [],
        visualDescription: "A blob of shifting colors and dimensions with tenticles that suction onto people's heads.",
        introduction: "Come, battle, and you shall be rewarded.",
        question: "What do you struggle for?",
        background: "When the Void Heretic returns to consume the stars, the energy of your violent struggle shall sustain me at the infinite-infinitesimal-battle",
        ideal: "Feel blessed that your minute existence will aid me during the collapse of the helix dimension.",
        bond: "",
        flaw: "The time it would take you to tire of immortality is but a moment of my existence.",
        skills: [],
        rewards: "A small pedant for each player based on the toughest monster they fought.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.dark,
        age: 0,
        race: "human",
        notoriety: "Only a couple shady people know about him.",    
        page: 1,
        id: 1,
        name: "Dark Blade",
        title: "Avenging Assasin",
        strength: 11,        
        dexterity: 18,
        constitution: 12,                
        intelligence: 10,                
        wisdom: 12,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 16,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Neutral",
        roleplayInspiration: "Killer Batman, Faceless man, edgelord.",
        motivation: "Killer for hire, but only for revenge",
        dmNotes: "Players can use him to kill other NPCs.",
        characterConnections: [],
        visualDescription: "A cloacked figure with a black bandana covering their lower face.",
        introduction: "I'm Darkblade, the last assasin on Freeside.",
        question: "Do you ",
        background: "I worship the gods of revenge.",
        ideal: "I'll kill anyone for 1000 as long as you can tell me why the deserve vengence.",
        bond: "When I pass my god will judge me by the balance I've brought to the world.",
        flaw: "I don't care who my target is, as long as long as someone wants revenge on them.",
        skills: [],
        rewards: "He'll kill another NPC in a couple days after contracted. They can't be revived.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.dragon,
        age: 200,
        race: "dargon",
        notoriety: "He's a regular at this bar.",    
        page: 1,
        id: 1,
        name: "Dargor",
        title: "Retired Actor",
        strength: 18,        
        dexterity: 15,
        constitution: 16,                
        intelligence: 15,                
        wisdom: 14,        
        charisma: 14,
        challengeRating: 2,
        armorClass: 15,
        hitPoints: 50,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Good",
        roleplayInspiration: "Retired Actor, Dramitc Performer, Tragic Diva",
        motivation: "Want's to know what happened to his old co-star",
        dmNotes: "This is an another entry point to the flower plot.",
        characterConnections: [],
        visualDescription: "A medium sized dragon wearing old, but well kept formal wear.",
        introduction: "Hello, I am the great fading star of the old opera, Dragor.",
        question: "So, what's the plot of your favorite opera?",
        background: "Decades ago me and my co-star thrilled audiences. She played the maiden, and I the villianous dragon!",
        ideal: "Nothings better than helping people believe good can triumph over evil.",
        bond: "Clarissa disapeared 50 years ago, and I still think of her to this day.",
        flaw: "I haven't been able to move on after her disapearance.",
        skills: [],
        rewards: "He'll give the players 1000 gold if they can find out what happened to Clarissa.",
        plotFlower: "Clarissa is one of the 5 people Lapith is currently keeping alive with the flower. Trying to track her down is an entry point to the flower plot.",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.lobi,
        age: 16,
        race: "halfling",
        notoriety: "People are used to her talking their ears off at the library.",    
        page: 1,
        id: 1,
        name: "Lobi",
        title: "Lore nerd.",
        strength: 9,        
        dexterity: 8,
        constitution: 12,                
        intelligence: 18,                
        wisdom: 10,        
        charisma: 13,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Sheldon, Fanboy, History Nerd.",
        motivation: "She wants to tell everything about all the amazing history she knows.",
        dmNotes: "She can used for lore dumps, or any lore questions the players have. She can also give clues.",
        characterConnections: [],
        visualDescription: "You student with a pile of books occasanliy looking up and trying to say hi to people.",
        introduction: "Hi, I'm Lobi, do you know that Freeside has actually been occupied by people for more than 6000 years?",
        question: "Have you been to the Tomb of Empires yet? There you can see every Empire that's ever had control of Freeside!",
        background: "I grew up here, did you know only 1 and 5 inhabitants of Freeside were born here?",
        ideal: "Learning about history honors the lives and struggles of all those who came before us! Did you know that the districts only were solidified in the last 200 years?",
        bond: "Oh, I'll be happy to just keep writting history books. We actually don't know who built the library or where the dogs came from. But the oldest stories of Freeside talk about 2 cults fighting over an object of immense value.",
        flaw: "I could keep going all day! What else do you want to know about?",
        skills: [],
        rewards: "",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.planithr,
        age: 23,
        race: "Half elf",
        notoriety: "One of the most popular and coolest people in freeside.",    
        page: 1,
        id: 1,
        name: "Planithir",
        title: "Party Promoter",
        strength: 11,        
        dexterity: 11,
        constitution: 11,                
        intelligence: 13,                
        wisdom: 14,        
        charisma: 9,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Good",
        roleplayInspiration: "",
        motivation: "Want's to throw a party bigger than then Eternal Ball.",
        dmNotes: "He'll flirt with the highest charisma player in the party.",
        characterConnections: [],
        visualDescription: "A thing attrative man in a fashionable white suit.",
        introduction: "Well hello there, look at this handsome bunch. I'm Planithir. If you clearly weren't new, you'd know that.",
        question: "What fun things bring you to Freeside?",
        background: "I've been here for quite some time, I'm on the list for every party.",
        ideal: "Fun and friends, what more is ther to life?",
        bond: "Freeside is a place where people can be truely free. I want to keep it like that.",
        flaw: "I will go down in history as the greatest host Freeside has ever known.",
        skills: [],
        rewards: "",
        plotFlower: "",
        plotConvoy: "He doesn't like the Convoy and thinks they're boring, but tolerates them.",
        plotParty: "He's the main entry point for planning a big party.",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.scholars,
        age: 75,
        race: "mixed",
        notoriety: "Known as regulars at the club",    
        page: 1,
        id: 1,
        name: "Pix, Wix, and Dix",
        title: "Arguing scholars",
        strength: 9,        
        dexterity: 9,
        constitution: 9,                
        intelligence: 18,                
        wisdom: 14,        
        charisma: 12,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Good",
        roleplayInspiration: "Three old coots at a bar, Quarlsome academics",
        motivation: "They love asking strangers about life's biggest questions.",
        dmNotes: "They're mostly here for a fun roleplaying opertunity.",
        characterConnections: [],
        visualDescription: "The scholars shouting and interupting each other.",
        introduction: "Ah, we haven't heard from you before!",
        question: "What would you say is the problem with the world? ",
        background: "I say it's the people work too much, they don't appreciate their lives!",
        ideal: "No, I say it's people don't work hard enough, what is your life other than your accomplisments!?",
        bond: "No no no, it's that there are too many ideas these days, people just can't ever settle on any one thing!? ",
        flaw: "Wait, let these fine people speak! So, what do you think the problem with the work is?",
        skills: [Skills.History, Skills.Insight, Skills.Arcana],
        rewards: "If players even try to answer at all they'll be delighted and give them a free pass to the library.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
 
    {
        code: CC.torbin,
        age: 50,
        race: "Dwarf",
        notoriety: "Known as the head of the yards",    
        page: 1,
        id: 1,
        name: "Torbin",
        title: "Ship Building master",
        strength: 12,        
        dexterity: 10,
        constitution: 15,                
        intelligence: 13,                
        wisdom: 9,        
        charisma: 11,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Neutral",
        roleplayInspiration: "J. Jona Jameson, Thomas Edison, Gimli",
        motivation: "Wants the Yards to run Freeside",
        dmNotes: "He's the most Pro convoy Freesider",
        characterConnections: [],
        visualDescription: "An overly serious dwarf wearing workers clothes but with an extra decorative hat.",
        introduction: "Get out of my way!",
        question: "Why am I wasting my time talking to you?",
        background: "I'm the Chief builder in the yards, and we're the ones that do all the work!",
        ideal: "What's there to do in life but work, and build!",
        bond: "We do all the work, we should be in charge of Freeside. Now the Convoy, they know how to run things!",
        flaw: "All these frivoulus fools in the Fire and Water district just play silly games, but do we get any thanks, never!",
        skills: [],
        rewards: "He'll try and get you to go beat up Bosworth.",
        plotFlower: "",
        plotConvoy: "He's pro convoy and is helping them setup their secret base. He wants them to move in and gain power for the yards that way.",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.trap,
        age: 45,
        race: "Human",
        notoriety: "Seen as a regular loner eccentric.",    
        page: 1,
        id: 1,
        name: "Trap",
        title: "Obssesed scholar.",
        strength: 9,        
        dexterity: 10,
        constitution: 9,                
        intelligence: 16,                
        wisdom: 14,        
        charisma: 8,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Evil",
        roleplayInspiration: "Snape, Dr. Frankenstien, Evil genius.",
        motivation: "He want's to open the book Kaiju book and control it.",
        dmNotes: "He's the simpliest hook to go into the dunegon and summon the Kaiju. He can barely pretend to be normal.",
        characterConnections: [],
        visualDescription: "A crazy looking scholar with tattered robes, unkept hair and a wild look in his eyes.",
        introduction: "Oh hello fine travellers, you look like a hearty bunch.",
        question: "Would you be interested in some work? I need a rare item retrieved, but I'm much to frail myself.",
        background: "It's a tome of ancient secretes, and I believe i've unravelled the key",
        ideal: "I seek the ancient truths others are afraid to believe in.",
        bond: "I keep to myself.",
        flaw: "I believe the book could benfit everyone on the island.",
        skills: [],
        rewards: "He'll give you 1000 gold for the book. If he finds you took the book, he'll try and hunt you down.",
        plotFlower: "The Kaiju was originally made by the flower cult to protect the island and the flower.",
        plotConvoy: "If players are able to conrol the Kaiju, they can use it to attack the Convoy Fleet.",
        plotParty: "",
        plotArena: "",
        plotKaiju: "He's the main entry point for summoning the Kaiju."    
    },
    {
        code: CC.wanwan,
        age: 99999,
        race: "Diety",
        notoriety: "Most people in freeside recognize hime",    
        page: 1,
        id: 1,
        name: "Wanwan",
        title: "Exiled party god.",
        strength: 18,        
        dexterity: 18,
        constitution: 18,                
        intelligence: 18,                
        wisdom: 18,        
        charisma: 18,
        challengeRating: 2,
        armorClass: 20,
        hitPoints: 100,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Neutral",
        roleplayInspiration: "Bachus, Mad Hatter.",
        motivation: "Is contrantly drunk and just wants to have fun.",
        dmNotes: "He's here to give players vague clues. He can show up anywhere. He doesn't have a great memory. He gets annoyed if the players ask too many questions.",
        characterConnections: [],
        visualDescription: "A hearty 7 ft tall bearded man laughing with a cup in his hand.",
        introduction: "Ah, friends, have a drink with me!",
        question: "What is your favorite way to relax.",
        background: "Yes, well I was kicked out of the heavenly palace some time ago. I took one too many sacred plums from the garden, or was it a pear?",
        ideal: "Yes, well we have all the time in the workd don't we! Have fun! Or, well, maybe you don't? But you know, there's that one woman in the purple cloak, I've seen her for quite  while!?",
        bond: "Of all the places in the material plane, Freeside is the most fun! Why even when those cultists were fussing about that flower it was still exciting!",
        flaw: "Yes well I've forgetten many things, but I don't think this Vazerith Empire will be taking over Freeside anytime soon!",
        skills: [],
        rewards: "As long as players act joyus with him he'll give vague clues.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.zaza,
        age: 40,
        race: "Human",
        notoriety: "She's the most influencial task maker in the Fire district.",    
        page: 1,
        id: 1,
        name: "Zaza",
        title: "Top play priducer.",
        strength: 11,        
        dexterity: 11,
        constitution: 11,                
        intelligence: 13,                
        wisdom: 18,        
        charisma: 16,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Oprah, Jackie O, Film Producer",
        motivation: "Wants to maintain the Fire district as a creative hub.",
        dmNotes: "She can lead the players to investigate the disentigrations/flower.",
        characterConnections: [],
        visualDescription: "Smartly dressed business woman, is always drinking potions.",
        introduction: "I'm Zaza, you'll learn about me sooner or later.",
        question: "You seem like a clever bunch. I could use some strangers to do a little detective work for me.",
        background: "I'm one of the top backers of theater in Freeside.",
        ideal: "Creativity and expression is the most important thing we do.",
        bond: "I want Freeside to remain a creative center as long as possible.",
        flaw: "",
        skills: [],
        rewards: "",
        plotFlower: "She'll give you clues about the disentigrations.",
        plotConvoy: "She doesn't want the convoy on Freeside at all.",
        plotParty: "She can help rally people.",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.yondo,
        age: 120,
        race: "3 headed person",
        notoriety: "One more the most popular food stalls.",    
        page: 1,
        id: 1,
        name: "Yondo",
        title: "3 headed chef.",
        strength: 13,        
        dexterity: 18,
        constitution: 12,                
        intelligence: 13,                
        wisdom: 15,        
        charisma: 12,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Good",
        roleplayInspiration: "TV Chef, but different personality per head.",
        motivation: "Wants to serve as many customers as possible.",
        dmNotes: "They can direct the player different places based on their repsonses.",
        characterConnections: [],
        visualDescription: "3 heads and 6 arms, rotating cooking and serving customers.",
        introduction: "Welcome. We've been having a discusion...",
        question: "If you're making a dish, what's the best way to do it?",
        background: "Head 1: You should plan it out, and not deviate, otherwise you'll never learn how to improve it!",
        ideal: "Head 2: No, you should only spice as you, always tasting be adjusting!",
        bond: "Head 3: No, No, it's all wrong, don't trust yourself so much, you should be asking the customers!",
        flaw: "What do you think?",
        skills: [],
        rewards: "They'll mention they've heard a legend about a flower petal that's tastes amazing, and they if you bring it to them you'll get a reward. Depending on your answers, they'll point you different locations.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.may,
        age: 150,
        race: "human",
        notoriety: "Used to be famous, but now no one knows her.",    
        page: 1,
        id: 1,
        name: "May",
        title: "Reluctant flower eater",
        strength: 9,        
        dexterity: 9,
        constitution: 9,                
        intelligence: 12,                
        wisdom: 13,        
        charisma: 15,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Good",
        roleplayInspiration: "Frightened senior, Aunt May, scared victim.",
        motivation: "Wants to stop Lapish, but doesn't know how.",
        dmNotes: "She's afraif to tell people about Lapish b/c she doesn't want to get others hurt. Can also be a red hearing for the disentigrator.",
        characterConnections: [],
        visualDescription: "Unassuming, but attrative 25 year old lady in a purple cloak.",
        introduction: "Oh, I'm sorry, I'm not able to talk.",
        question: "Why, why do you want to talk to me.",
        background: "I used to be in the theater, and my husband was a wealthy man. When he passed, he set me up a fund, and bought me into a circle of people.",
        ideal: "I've already been alive longer thatn I should have, there's only so many memories I can have, I don't need to keep going.",
        bond: "I've seen Lapish kill dozens of people, whenever anyone goes against her will in the slightest, she'll disentigrate them. I just want her stopped.",
        flaw: "I'm too weak to fight her myself, she has rings that let her cast spells, and she has a huge amount of money.",
        skills: [Skills.Performance, Skills.Acrobatics, Skills.Insight],
        rewards: "She'll help you find and battle Lapish.",
        plotFlower: "You can identify her from a picture of Dragor. She'll be able to lay out the whole immortality plot if needed.",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.queen,
        age: 60,
        race: "human",
        notoriety: "Everyone knows the current queen of the fools court, but they don't last more than a year or two.",    
        page: 1,
        id: 1,
        name: "The Queen",
        title: "Fools Court Monarch",
        strength: 10,        
        dexterity: 10,
        constitution: 10,                
        intelligence: 14,                
        wisdom: 8,        
        charisma: 15,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Chaotic Nuetral/Evil",
        roleplayInspiration: "The Red Queen, Bloody Mary, Ru Paul",
        motivation: "Wants to rule the court with an iron fist.",
        dmNotes: "The fools court is a fun version of tyrany. Everyone loves when the reigning monarch has dramatic rise and falls. The people also re-enact the real life politics of Freeside as a form of political debate. People will get 'killed', which means they have to show up as a new character next time. ",
        characterConnections: [],
        visualDescription: "An extremely huge and elaborate dress that's hard for her to mvoe around in.",
        introduction: "Your queen has arrived!",
        question: "What is the punishment for such insolence, I say DEATH!",
        background: "These amabassadors from the small island of flipflap are refusing to let me build my makeup cosmetics facotry.",
        ideal: "The entire purpose of this court is to celebrate my beatury! These scum dare challenge that!?",
        bond: "Through my legacy, you sad courtiers will be known forever, I do all of this for my people.",
        flaw: "No one would ever dare challenge my reign.",
        skills: [Skills.Performance, Skills.Intimidation, Skills.Insight],
        rewards: "Having influence over the Fools Court can translate into shapping the current beliefes of people on Freeside. If the players can successfully influnce the court, it'll have real life repurcussions.",
        plotFlower: "",
        plotConvoy: "Freeside's general feelings about The Convoy can be shaped here.",
        plotParty: "",
        plotArena: "",
        plotKaiju: ""    
    },
    {
        code: CC.gods,
        age: 99999,
        race: "gods",
        notoriety: "Possibly recognizable gods to the PC's",    
        page: 1,
        id: 1,
        name: "The 3 Gods",
        title: "Watching Freeside",
        strength: 99,        
        dexterity: 99,
        constitution: 99,                
        intelligence: 99,                
        wisdom: 8,        
        charisma: 99,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Neutral Neutral",
        roleplayInspiration: "Greek, Hindu or Norse Gods with different qualities.",
        motivation: "Are gambling on the outcomes of Freeside.",
        dmNotes: "They're mostly meant to be spooky and moody, and possibly give the players a wish scroll. They can appear anywhere, but ideally in a cave that the Kaiju comes out of.",
        characterConnections: [],
        visualDescription: "3 20 ft dieties sitting around a large puddle that they're watching humans through.",
        introduction: "Hello mortals. We've been watching you.",
        question: "How do you think it makes us feel to watch you mortals?",
        background: "God 1: It makes me weep.",
        ideal: "God 2: It makes us smile.",
        bond: "God 3: It makes us laugh.",
        flaw: "See, even we cannot agree. So what do we do to pass the time? We gamble.",
        skills: [Skills.Performance, Skills.Intimidation, Skills.Insight],
        rewards: "If the players answer any reasonable response, they gods give them a wish scroll.",
        plotFlower: "",
        plotConvoy: "",
        plotParty: "",
        plotArena: "",
        plotKaiju: "They appear in a cave that was formed outside of where the Kaiju was buried."    
    },
    {
        code: CC.master,
        age: 25,
        race: "human",
        notoriety: "No one really knows him, he could be any Convoy official to most people.",    
        page: 2,
        id: 2,
        name: "Manlintine",
        title: "Convoy Elite",
        strength: 13,        
        dexterity: 12,
        constitution: 12,                
        intelligence: 13,                
        wisdom: 13,        
        charisma: 13,
        challengeRating: 2,
        armorClass: 12,
        hitPoints: 20,
        speed: 30,
        passivePerception: 10,
        proficiencyBonus: 2,        
        attack:{
            bonus: 5,
            range: 5,
            multi: 1,
            damage: "1d8",                        
        },
        spells: [],
        alignment: "Lawful Evil",
        roleplayInspiration: "Tech Bro, Wealthy Snobby Brat, King Joffery",
        motivation: "Wants to be known for great things himself.",
        dmNotes: "This is main vilian figure of the Convoy. Plenty of convoy people hate him too. He wants to lead the Convoy fleet into Freeside and take all the glory.",
        characterConnections: [],
        visualDescription: "An arrogant young man in a convoy uniform lined with gold thread on the seems.",
        introduction: "Get out of my way, I have business to attend to.",
        question: "Why should I even ",
        background: "I'm from the greatest Convoy family, we can trace our line back to the first captains.",
        ideal: "The Convoy is the strongest institution that ever has existed, or will exist, and I'm it's most important leader.",
        bond: "Me and my family were born to lead.",
        flaw: "Everyone listens to what I say, or else.",
        skills: [Skills.Intimidation, Skills.Performance, Skills.Persuasion],
        rewards: "If the players side with the Convoy, and help the fleet setup at the base, he'll give them a huge amount of money.",
        plotFlower: "If he finds out about the flower, he'll stop at nothing to get his hands on it for himself.",
        plotConvoy: "He just recently found out about the secret harbor and fleet, and he swooped in to lead it and take all the credit.",
        plotParty: "",
        plotArena: "",
        plotKaiju: "He'll pretend like he's leading troops to fight, but will behind the lines."    
    },
]


export interface Location {
    code: LC;
    page?: number;
    id?: number;
    name: string;
    exterior: string;
    interior: string;
    detailOne: string;
    detailTwo: string;
    crowd: string;
    connectedAreas: LC[];
    namedNpcs: CC[];
    dmNotes: string;
    events: string[];
    randomNpcs: RandomNpc[];
}

// ===== Locations ======================
export const locations: Location[] = [
{
    // ++++  L1 - Landing Area ++++
    name: "Freeside Landing Area",
    code: LC.land,
    page: 1,
    id: 1,
    exterior: "A chaotic dock with no order. Boats are bumping and pushing.",
    interior: "People are loading and unloading goads quickly through a disorderly crowd.",
    crowd: "All kinds of people, generally a little shabby. Everyone\"s busy.",
    detailOne: "Across the bay you can see ships being easly guided into an organized port.",
    detailTwo: "There don't seem to be any kind of athorities managing the docks.",
    dmNotes: "This is just a starting area, there\"s no reason to come back here.",
    connectedAreas: [LC.pcafe, LC.convoy],
    namedNpcs: [],
    events: [
        "Palyers will get handed a discount to the Grand Galleria, and a free drink coupon to the Merchants plaza",
        "The players will get caught in the middle of a fight between Convoy sailors and a group od pirates.",    
    ],
    randomNpcs: [
        {
            name: "Baggins",
            race: "Gnome",
            job: "Refugee",
            description: "Angry",
            dialogue: "After my country was invaded by Orcs, this was the only place I could go.",
        },
        {
            name: "Toms",
            race: "Giant Bird",
            job: "Merchant",
            description: "Bossy",
            dialogue: "Carful getting those eggs of the boat!",
        },
        {
            name: "Candice",
            race: "Elf",
            job: "Mercenary",
            description: "Intense",
            dialogue: "I'm just here to find work, hopefully I don't have to stay in this pit too long.",
        }
    ]
},
{
    // ++++  L2 - Pirate Cafe ++++
    code: LC.pcafe,
    name: "Pirate Cafe",
    exterior: "A ramshackle building with an ruckus party going on outside.",
    interior: "A large tavern and meeting hall with hundreds of flags on all the walls.",
    detailOne: "When ever someone passes out, they\"re dragged into a big nap room in the back.",
    detailTwo: "People are betting on 2 crabs fighting with little fencing swords",
    connectedAreas: [LC.land, LC.orc],
    namedNpcs: [CC.boz],
    crowd: "2/3 Pirates of all kinds, and 1/3 a big variery of people.",
    dmNotes: "This cafe is known for unregulated deals. This can act as a base of anti-Convoy activities.",
    events: ["If the players approach Bozfiled, he\"ll try and recruit them to help fight the Convoy"],
    randomNpcs: [
        {
            name: "Cluster",
            race: "Goblin",
            job: "Pirate Map Maker",
            description: "Agitated",
            dialogue: "I hate the Convoy!",
        },
        {
            name: "Nigal",
            race: "Human",
            job: "Shabby Merchant",
            description: "Excited",
            dialogue: "Maybe when they Convoy comes, they\"ll hire me!?",
        },
        {
            name: "Boomer",
            race: "Dwarf",
            job: "Pirate Craftsman",
            description: "Joyful",
            dialogue: "The more Freeside changes, the more it stays the same!?",
        }
    ]

},
{
    // ++++  L3 - Convoy Building ++++
    name: "Convoy Office",
    code: LC.convoy,    
    exterior: "A small 1 floor, freshly painted building with a Convoy flag.",
    interior: "A single room with a door to a barracks and a desk with a man sitting at it.",
    crowd: "Only one person politely waiting at the desk.",
    detailOne: "No decorations except a painting of a fleet of Convoy ships.",
    detailTwo: "The door to the barracks is locked",
    dmNotes: "The locked door is an entrance to the secret Convoy base.",
    connectedAreas: [LC.land],
    namedNpcs: [CC.conrad],
    events: [
        "Conrad will try to recuit the Convoy. His first assigment is to do a pro-Convoy story at the Fools Court.",        
    ],
    randomNpcs: 
        [
            {
                name: "Travis",
                race: "Human",
                job: "Guard",
                description: "Bored",
                dialogue: "Reporting Sir, no suspecious activity.",
            },
    ]
},
{
    // ++++  L4 - Orc Tavern ++++
    name: "Orc Tavern",
    code: LC.orc,    
    exterior: " huge yurt with crude paintings on the exterior and orcs mullings around.",
    interior: "Orcs and a couple non orcs mull around. Orcs ocasinially get in fist fights.",
    crowd: "Mostly orcs, but a couple non orcs are socializing. The fighs all end without deaths.",
    detailOne: "The biggest orc sits on a thrown in one end of the yurt.",
    detailTwo: "After fights have stopped, the orcs go back to being friendly.",
    dmNotes: "THe orcs are a recrutible gang for the players. They won't kill ir die for them, but they'll beat people up and intimidate them.",
    connectedAreas: [LC.pcafe],
    namedNpcs: [],
    events: [
        "Crap Face will challenge the players to unarmed combat.",        
    ],
    randomNpcs: [
        {
            name: "Ug Muck",
            race: "Orc",
            job: "Bouncer",
            description: "Joyful",
            dialogue: "We jus' got paid, I just spent my money on the tastiest pus beetles I know!",
        },
        {
            name: "Dumb Butt",
            race: "Orc",
            job: "Docker Worker",
            description: "Harty",
            dialogue: "I don't like those convoy lugs moving in there. Have you seen how big their ships are, where they gonna put 'em!?",
        },
        {
            name: "Blorb Blorb",
            race: "Orc",
            job: "Bank Security Guard",
            description: "Harty",
        dialogue: "I used to fight in armies, but I didn't know true joy until I came here!",
        },
    ]
},
{
    name: "The Eternal Ball",
    code: LC.ball,    
    exterior: "A block size orantely decorated warehouse.",
    interior: "A series of large rooms with differnt kinds of party activities going on.",
    crowd: "A huge variety of people, dancing, socializing, eating, listening to performaces.",
    detailOne: "A bar room with wizards float glasses around and making ice cubes with spells.",
    detailTwo: "There's a trio of giants playing huge drums in a big dance hall.",
    dmNotes: "Make up whatever fun details you want for different party rooms. Any NPC can show up here.",
    connectedAreas: [LC.opera, LC.gate],
    namedNpcs: [CC.ban, CC.zaza, CC.chit],
    events: [],
    randomNpcs: [
        {
            name: "Lindy",
            race: "Bird Person",
            job: "Mercenary",
            description: "joyful",
            dialogue: "this is my favorite place to come after a bit battle.",
        },        
        {
            name: "Bushi",
            race: "Crab Person",
            job: "Convoy Diver",
            description: "Sullen",
            dialogue: "They ran out of the drink I wanted",
        },        
        {
            name: "Dub Dub",
            race: "Human",
            job: "Wizard",
            description: "Excited",
            dialogue: "My dream is to become a party mage, know anyone I can talk to?",
        },        
    ]
},
{
    name: "The Bank",
    code: LC.bank,    
    exterior: "An almost perfectly square building with a fewer windows and high ceilings, about the size of a city block.",
    interior: "A small seating area with a queue to let people in. Then dozens of desks wil bankers and clients talking.",
    crowd: "Not very packed, banks and merchants sitting at desks, making deals.",
    detailOne: "After shaking, the customers get a ring put on their finger.",
    detailTwo: "The bankers activate a zone of truth when around their desk when they start talking to you.",
    dmNotes: "The bank is meant to let players find creative things to do with theur money.",
    connectedAreas: [LC.merchant],
    namedNpcs: [CC.planithr],
    events: [],
    randomNpcs: [
        {
            name: "Kol",
            race: "Halfling",
            job: "Banker",
            description: "A professional halfing in a unifrom.",
            dialogue: "So, what sort of loan are you interested in.",
        },        
    ]
},
{
    name: "Club Deluxe",
    code: LC.club,    
    exterior: "A3 story building totally covered in gold.",
    interior: "The nicest spa/resort/restuaunt/bar you've ever been in. There's a 1000 gold 1 year membership fee for the party.",
    crowd: "Not too packed, everyone's ",
    detailOne: "If someone is rude to the staff, they're escorted out immediately.",
    detailTwo: "",
    dmNotes: "If they PC's get access here, they should meet most powerful people in Freeside.",
    connectedAreas: [LC.bank],
    namedNpcs: [CC.zaza, CC.torbin, CC.caspian],
    events: [],
    randomNpcs: [
        {
            name: "Dorolp",
            race: "Dwarf",
            job: "Famous Sculptor",
            description: "Relaxed",
            dialogue: "Sorry, I don't want to talk about business while I'm here.",
        },        
        {
            name: "Charles",
            race: "Human",
            job: "Waiter",
            description: "Engaged",
            dialogue: "Welcome, would you like to be introduced to anyone?",
        },        
        {
            name: "Pippin",
            race: "Fairy",
            job: "Merchant",
            description: "Talkative",
            dialogue: "Wanna hear about the latest best sellers at the market?",
        },        
    ]
},
{
    name: "Hinterland Commune",
    code: LC.comune,    
    exterior: "A cozy looking villaige",
    interior: "Not much decoration, but very well laid out villaige",
    crowd: "Everyone seems really happy and friendly, but some involved sounding debates over small stuff",
    detailOne: "A bulletin board with people requesting help with tasks.",
    detailTwo: "Another bulletin board with suggestions for adding or removing rules for the villiage.",
    dmNotes: "This is mostly a juntion to the ghost house.",
    connectedAreas: [LC.gate, LC.ghost],
    namedNpcs: [],
    events: [],
    randomNpcs: [
        {
            name: "Jambo",
            race: "Human",
            job: "Farmer",
            description: "Angry",
            dialogue: "Gabbins farm has been producing more than mine! Is he taking extra fertalizer?",
        },        
        {
            name: "Curtis",
            race: "Centaur",
            job: "Cart puller",
            description: "Helpful",
            dialogue: "I was never appreciated where I grew up, but now everyones always asking for help!",
        },        
        {
            name: "Casilla",
            race: "Tabxi",
            job: "Cart puller",
            description: "Lazy",
            dialogue: "I cook all the meals so I can just lay around in the sun all day.",
        },    
    ]
},
{
    name: "Fools Court",
    code: LC.court,    
    exterior: "A tiny fantasy castle, like disney land.",
    interior: "A huge count with high ceilings looking out over a fantasy landscape.",
    crowd: "Everys dressed crazy and overacting, pretending they're from fantasy kingdoms.",
    detailOne: "There's a semi-choaregraphed dance going on in one area with a band playing.",
    detailTwo: "There's a baquete table laid out in front of a throne.",
    dmNotes: "It's a LARP. Players can come here to try and exert political influence over Freeside. Whatever's happening in Freeside, should be mirrored here, but in a silly way. If any fights happen, players must do perforamce and acrobatics checks.",
    connectedAreas: [LC.opera, LC.ball],
    namedNpcs: [],
    events: ["When the players first arrive, there's a drama being played out of the queen wanting to invade a small, sacred island to set up a new beauty salon.", 
"When the queen arrives, she'll she the players are new. She'll ask them whether or not she should invade the country and set up a new base."],
    randomNpcs: [
        {
            name: "Captain Fumblebum",
            race: "Draconic",
            job: "Royal Food ",
            description: "A vest of peacock feathers",
            dialogue: "Our queen doesn't care about other countries, she only wants power!",
        },        
        {
            name: "BiBum",
            race: "human",
            job: "Ambasador of FlipFlap",
            description: "A ragged peasant.",
            dialogue: "Please, your majesty, your makeup factory is right in a fishing cove we need to feed our families.",
        },        
        {
            name: "Floofy",
            race: "saytr",
            job: "Court Jester",
            description: "A bright red skin tight leather suit.",
            dialogue: "Maybe if the queen was prettier, this poor island could be saved!?",
        }, 
    ]
},
{
    name: "Ghost House",
    code: LC.ghost,    
    exterior: "A large decaying mansion blcoking a mountain pass. ",
    interior: "Rotting walls, cobwebs, damaged paintings and artifacts.",
    crowd: "Ghosts of the original Flower cult members.",
    detailOne: "Small flower patterns are drawn into some of the walls.",
    detailTwo: "You can hear voices coming from behind walls, but they seem to move around.",
    dmNotes: "If the characters can fly over it, it's ok to let them. This leads right to the Dungeon C.",
    connectedAreas: [LC.comune],
    namedNpcs: [],
    events: [],
    randomNpcs: [
        {
            name: "",
            race: "",
            job: "",
            description: "",
            dialogue: "",
        },        
    ]
},
{
    name: "The Grand Gallery",
    code: LC.gallery,    
    exterior: "A building built around the street with a glass sealing covering it.",
    interior: "3 stories of shopws of all kinds ",
    crowd: "",
    detailOne: "",
    detailTwo: "",
    dmNotes: "THe players can purchase any official magic item here.",
    connectedAreas: [LC.yards, LC.gate, LC.merchant],
    namedNpcs: [],
    events: ['Make sure to call out the entrance to dungeon D2'],
    randomNpcs: [
        {
            name: "Blip",
            race: "Goblin",
            job: "Alchemist",
            description: "Searching",
            dialogue: "I just need to find the whisker shop, I know it's around here.",
        },        
        {
            name: "Thomas",
            race: "Elf",
            job: "Figher",
            description: "Satisfied",
            dialogue: "With this magic sword I can finally take on the ghosts plaguing my people.",
        },        
        {
            name: "Crystal",
            race: "Human",
            job: "Cleric",
            description: "Angry",
            dialogue: "They sold the last icon of my god, and they don't know when the next one is coming in.",
        },        
    ]
},
{
    name: "The Dead Gate",
    code: LC.gate,    
    exterior: "A crumbling wall and ruins around a crumbling doorless gate on the main road to the hinterlands.",
    interior: "Around the ruins is a huge old cemetary filled with statues and tombs.",
    crowd: "There's light foot traffic of people travelling to the hinter lands, or people visiting graves..",
    detailOne: "The Tomb of Empires is a large tomb that lists out all the empires that have ruled over freeside, includeing another dozen empty spaces.",
    detailTwo: "There seems to be a compettion around what gravesite can be made the most elaborate.",
    dmNotes: "The players can engage with Patricia to get n entry into the flower plot.",
    connectedAreas: [LC.gallery, LC.ball],
    namedNpcs: [], // make sure to add patricia.
    events: ["The players can go examine the Tomb of empires.", "They players can see someone laying a flower on the grave of someone who's marked as dying 200 years ago."],
    randomNpcs: [
        {
            name: "Poom",
            race: "Human",
            job: "Farmer",
            description: "Satisfied",
            dialogue: "Just sold my entire harvest of green berries, I knew there was a fad!",
        },        
        {
            name: "Frank",
            race: "Turtle Person",
            job: "Fisherman",
            description: "Determinde",
            dialogue: "Not many people venture out to the comunes, it's a bit boring there. But I think that's why they'll pay a premium for these fish!",
        },        
    ]
},
{
    name: "Gladiator Areana",
    code: LC.glad,    
    exterior: "A huge areana like the Coliseum. Magic made illusions and fireworks play outside.",
    interior: "A colorful crowd with vendors walking around. It's like one big party.",
    crowd: "Everyone's excited and cheering at the fights.",
    detailOne: "Dancers and music play inbetween fights. Bet takers walking around and everyone's betting with each other.",
    detailTwo: "During fights the audeince will throw potions to the combatants. Healers save people from getting killed.",
    dmNotes: "If thr players joing the fights, they'll gain money and fame.",
    connectedAreas: [LC.pcafe, LC.land, LC.convoy],
    namedNpcs: [CC.bosph],
    events: ["THe first time the players come, they'll try to be recuited as fighters."],
    randomNpcs: [
        {
            name: "Molly",
            race: "Dwarf",
            job: "Food Vendor",
            description: "Chearing",
            dialogue: "I can't wait until the whirling trio are up, I'm gonna bet my weeks wages on them! ",
        },        
        {
            name: "Dizonene",
            race: "Human",
            job: "Singer",
            description: "Sad",
            dialogue: "My brother just lost another fight.",
        },        
        {
            name: "Krandor",
            race: "Minotaur",
            job: "Bookie",
            description: "Friendly",
            dialogue: "Wanna make a bet? Makes watching a lot more fun.",
        },        
    ]
},
{
    name: "Dog Library",
    code: LC.library,    
    exterior: "A large library with a statue of a sitting dog with a book in it's mouth.",
    interior: "A reading area with people reading books. Next to it is a roped off area of endless seeming stacks of books. Visitors walk up to the ropes with offerings of food and a dog comes up to take. The dog then runs to fetch the book and bring it back. Books cannot be taken out of the library.",
    crowd: "A mix of scholars and students from all over.",
    detailOne: "Some people give the dogs new books, they'll then return with a small bag of gold.",
    detailTwo: "The dogs will snarl at anyone that gets too close to crossing the rope, but are otherwise very friendly.",
    dmNotes: "No one knows when the library was built or where the dogs came from. Let players get creative with the books they might ask for.",
    connectedAreas: [LC.merchant],
    namedNpcs: [CC.lobi, CC.trap],
    events: ['Trap will approach the players and try to get them to retrieve the lost book.'],
    randomNpcs: [
        {
            name: "Constance",
            race: "Lizard Person",
            job: "History Professor.",
            description: "Melancholy",
            dialogue: "I came here to reasearch the history of my people, but I've found little.",
        },        
    ]
},
{
    name: "Merchant Plaza.",
    code: LC.merchant,    
    exterior: "A large plaza with food stalls all around the edges.",
    interior: "Merchants are walking around making deals and signing contracts. Lots of foot traffic around the food stalls.",
    crowd: "All variety of merchants and sailors making deals. A larger variety of people are here for the food stalls.",
    detailOne: "All deals are public and a crowd watches the negotiants. When a deal is completed, a cheer goes up.",
    detailTwo: "There's a giant talking chicken making omletes from her own eggs.",
    dmNotes: "This is like the main hub of the Water District. Make the players pick between talking to Ann or Caspian.",
    connectedAreas: [LC.glad, LC.gate, LC.bank, LC.library],
    namedNpcs: [CC.caspian], // Need to add Ann and 3 headed cook.
    events: ["Caspian will try to talk to the PC's"],
    randomNpcs: [
        {
            name: "Boris",
            race: "Elf",
            job: "Fruit Merchant",
            description: "Happy",
            dialogue: "Finally I found a good price on green berries.",
        },        
        {
            name: "Catherine",
            race: "Human",
            job: "Chef",
            description: "Inviting",
            dialogue: "Come try my green berry pie!",
        },        
        {
            name: "Burdo",
            race: "Half Orc",
            job: "Foodie",
            description: "Interested",
            dialogue: "I come to Freeside once a year just to see what new stalls have opened up.",
        },        
    ]
},
{
    name: "The Yards",
    code: LC.yards,    
    exterior: "A buisey ship building aread full or warehouses and ports.",
    interior: "Hustling and busling, unloading ships, building new ones, and repairing them.",
    crowd: "Workers and sailors moving all over.",
    detailOne: "Giants and magicians are used for all kinds of physical labor.",
    detailTwo: "Workers wear different colors of uniform based on their role.",
    dmNotes: "The workers here are pretty friendly and open, and will share info with the players. If players want to investigate anything, this is best place to start.",
    connectedAreas: [LC.gate, LC.gallery],
    namedNpcs: [CC.torbin],
    events: ["When the players first arrive, Torbin can bump into them and he'll ne annoyed ny them."],
    randomNpcs: [
        {
            name: "Kazor",
            race: "Giant",
            job: "Lifter",
            description: "Happy",
            dialogue: "Nothing's as good for you as a hard days work.",
        },        
        {
            name: "Bondu",
            race: "Human",
            job: "Wizard",
            description: "Intense.",
            dialogue: "The price of granit and timber has been up a lot recently, but I havrn'y seen many more ships being nuolt. I wonder there it's all going.",
        },        
        {
            name: "Picky",
            race: "Gnome",
            job: "Accountant",
            description: "Flustered",
            dialogue: "The districts have been keeping things nice and stable for the last 200 years. I can only hope it continues.",
        },        
    ]
},
{
    name: "Opera Caberte",
    code: LC.opera,    
    exterior: "A bar you have to walk downstairs to.",
    interior: "A smokey lounge a caberete with opera being performed on a small stage.",
    crowd: "Groups of friends sitting at tables getting table service.",
    detailOne: "The host is a fairy, flying around to guests and checking on them, and collecting money for the performer inbetween songs.",
    detailTwo: "A group of bards are compising songs together at a table in the corner.",
    dmNotes: "Have the players only be able to talk to one of the NPCs before the others leave.",
    connectedAreas: [LC.ball, LC.gate],
    namedNpcs: [CC.scholars, CC.dragon, CC.cloaked],
    events: [],
    randomNpcs: [
        {
            name: "Chris",
            race: "Dog person",
            job: "Construction wizard",
            description: "Content",
            dialogue: "I just come here to relax after a day of hard work.",
        },        
        {
            name: "Willis",
            race: "Human",
            job: "Actor",
            description: "Chatty",
            dialogue: "I always come here for a drink before going to the Eternal Ball.",
        },   
        {
            name: "Cozy",
            race: "Halfling",
            job: "Bard",
            description: "contemplative",
            dialogue: "There hasn't been a new opera in a while.",
        },             
    ]
},
{
    name: "Mound",
    code: LC.mound,    
    exterior: "A small hill with a stone piller on it.",
    interior: "There's writting on the stone pillar",
    crowd: "Just some birds, and some kids playing.",
    detailOne: "The stone says 'The great protector'",
    detailTwo: "",
    dmNotes: "This location is just here as a clue. It's also where the Kaiju appears out of when summoned.",
    connectedAreas: [LC.comune, LC.ghost],
    namedNpcs: [],
    events: [],
    randomNpcs: [
        {
            name: "Julie",
            race: "Halfling",
            job: "child",
            description: "Playing",
            dialogue: "Uhm, the kids come here to play, it's fun to role down the hill.",
        },                      
    ]
},
]    


export const l = (code: LC) => {
    const loc = locations.filter((location) => {
        return location.code === code.toString();
    })[0]
    return  loc as Location    
}

export const c = (code: CC) => {   
    return characters.filter((npc) => {
        return npc.code === code.toString();
    })[0] as Character    
}


const addId  = (arr: any[]) => {
    let lCount = 1;
    let cCount = 1; 
    let newArr = [...arr];
    newArr.forEach((item, pageNumber) => {
        // it's a location.
        if(item.exterior || item.exterior === '') {
            item.id = lCount;
            lCount += 1;
        } else if(item.ideal || item.ideal === '') {
            item.id = cCount;
            cCount += 1;
        }
        item.page = pageNumber + 1;
    });
    return newArr;
};

export const pages: any[] = addId([
    l(LC.land),
    l(LC.pcafe),
    c(CC.boz),
    l(LC.convoy),
    c(CC.conrad),
    l(LC.orc),
    c(CC.crap),
    c(CC.dark),
    l(LC.glad),
    c(CC.bosph),
    l(LC.merchant),
    c(CC.caspian),
    c(CC.yondo),  
    c(CC.ann),        
    l(LC.library),
    c(CC.trap),
    c(CC.lobi),
    l(LC.bank),
    c(CC.planithr),    
    l(LC.yards),
    c(CC.torbin),
    c(CC.master),    
    l(LC.gallery),
    c(CC.wanwan),
    l(LC.gate),  
    c(CC.may),          
    l(LC.opera),    
    c(CC.dragon),
    c(CC.scholars),
    c(CC.cloaked),
    l(LC.ball),
    c(CC.chit),
    c(CC.ban),
    c(CC.zaza),
    l(LC.court),
    c(CC.queen),
    l(LC.comune),
    c(CC.artok),
    l(LC.mound),
    l(LC.ghost),
])




